### PR TITLE
added quotes android project files

### PR DESCRIPTION
**Pull request by Samarthasbhat**

### CODE REVIEW

**Comment by sunkusaarthak** [comment]
Hay can you please create a folder named your project and add all those files to that folder
So, it would be helpful to maintain the file structure. #3

**Comment by Samarthasbhat** [comment]
How to create a folder in your repository can you please tell me

**Comment by Samarthasbhat** [comment]
completed the issue

**Comment by sunkusaarthak** [comment]
Successfully Merged

**Pull request merged**
